name: CMake
on:
  workflow_dispatch:
      inputs:
        extra_resolve_options:
          description: "Extra Resolve Options"
          required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.resolve_options }}
jobs:
  docker_builds:
    strategy:
      fail-fast: false
      matrix:
        config:
          - container: ghcr.io/steinwurf/python-bindings:latest
            name: Cmake 3.16.3 (GCC)
    runs-on: [self-hosted, docker, builder]
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CMake Cleanup
        run: cmake -E remove_directory build
      - name: CMake Setup
        run: cmake -E make_directory build
      - name: CMake Configure
        working-directory: ${{github.workspace}}/build
        run: cmake ../ -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@ $EXTRA_RESOLVE_OPTIONS"
      - name: CMake Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
